/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nup_z_NupJni */

#ifndef _Included_nup_z_NupJni
    #define _Included_nup_z_NupJni
    #ifdef __cplusplus
extern "C" {
    #endif
/*
 * Class:     nup_z_NupJni
 * Method:    on_gl_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nup_z_NupJni_on_1gl_1surface_1created(
    JNIEnv*, jclass);

/*
 * Class:     nup_z_NupJni
 * Method:    on_gl_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nup_z_NupJni_on_1gl_1surface_1changed(
    JNIEnv*, jclass, jint, jint);

/*
 * Class:     nup_z_NupJni
 * Method:    on_gl_surface_draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nup_z_NupJni_on_1gl_1surface_1draw(JNIEnv*, jclass);

    #ifdef __cplusplus
}
    #endif
#endif
